
CREATE TABLE IF NOT EXISTS users (
id INT primary key generated by default as identity,
email VARCHAR(128) not null UNIQUE,
login VARCHAR(128) not null,
birthday DATE);

create table if not exists friends (
user_id INT references users(id),
friend_id INT references users(id),
constraint friends_relation_uq UNIQUE(user_id, friend_id),
constraint user_friend_not_eq check (user_id <> friend_id)
);


create table if not exists genres (
id INT primary key,
genre VARCHAR(64));

create table if not exists ratings (
id INT primary key,
rating VARCHAR(5));

create table if not exists films (
id INT primary key generated by default as identity,
name VARCHAR(128) not null,
description VARCHAR(200),
release_date DATE,
duration INT,
genre_id INT references genres(id),
rating_id INT references ratings(id));



create table if not exists likes (
film_id INT references films(id),
user_id INT references users(id),
constraint film_user_uq UNIQUE(film_id, user_id)
);

create table if not exists films_genres (
film_id INT references films(id),
genre_id INT references genres(id),
constraint film_genre_uq unique(film_id, genre_id));