DELETE FROM FRIENDS;
DELETE FROM FILMS_GENRES;
DELETE FROM LIKES;
DELETE FROM FILMS;
ALTER TABLE FILMS ALTER COLUMN ID RESTART WITH 1;
DELETE FROM USERS;
ALTER TABLE USERS ALTER COLUMN ID RESTART WITH 1;

INSERT INTO users (email, login, birthday, name)
VALUES ('alex@mail.il', 'alex', '2000-12-01', 'Алексей Фролович');
